// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NTRSimulator.Database.Core;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NTRSimulator.Database.Migrations
{
    [DbContext(typeof(NTRSimulatorDbContext))]
    [Migration("20260627041433_RenameGunToGunEntity")]
    partial class RenameGunToGunEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NTRSimulator.Database.Entities.Account", b =>
                {
                    b.Property<long>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Uid"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TimeLastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Uid");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("NTRSimulator.Database.Entities.AvgDuo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountUid")
                        .HasColumnType("bigint");

                    b.Property<long[]>("AvgDuoMainStageIds")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint[]")
                        .HasDefaultValue(new long[0]);

                    b.Property<long[]>("AvgDuoSubStageIds")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint[]")
                        .HasDefaultValue(new long[0]);

                    b.HasKey("Id");

                    b.HasIndex("AccountUid")
                        .IsUnique();

                    b.ToTable("AvgDuos");
                });

            modelBuilder.Entity("NTRSimulator.Database.Entities.Costume", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountUid")
                        .HasColumnType("bigint");

                    b.Property<long>("CostumeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AccountUid");

                    b.HasIndex("CostumeId");

                    b.ToTable("Costumes");
                });

            modelBuilder.Entity("NTRSimulator.Database.Entities.GunEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountUid")
                        .HasColumnType("bigint");

                    b.Property<long>("CostumeId")
                        .HasColumnType("bigint");

                    b.Property<long>("GunId")
                        .HasColumnType("bigint");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountUid");

                    b.HasIndex("GunId");

                    b.ToTable("Guns");
                });

            modelBuilder.Entity("NTRSimulator.Database.Entities.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountUid")
                        .HasColumnType("bigint");

                    b.Property<int>("Count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("AccountUid", "ItemId")
                        .IsUnique();

                    b.ToTable("Items");
                });

            modelBuilder.Entity("NTRSimulator.Database.Entities.Weapon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountUid")
                        .HasColumnType("bigint");

                    b.Property<int>("BreakTimes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<long>("CurExp")
                        .HasColumnType("bigint");

                    b.Property<long>("GunId")
                        .HasColumnType("bigint");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("WeaponId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AccountUid");

                    b.HasIndex("GunId");

                    b.HasIndex("WeaponId");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("NTRSimulator.Database.Entities.WeaponMod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountUid")
                        .HasColumnType("bigint");

                    b.Property<long>("Field5")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<long>("Field6")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<decimal>("Field7")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasDefaultValue(0m);

                    b.Property<long>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<decimal>("Uid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<long>("WeaponModId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.HasIndex("WeaponModId");

                    b.HasIndex("AccountUid", "WeaponModId")
                        .IsUnique();

                    b.ToTable("WeaponMods");
                });

            modelBuilder.Entity("NTRSimulator.Database.Entities.WeaponModSkin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountUid")
                        .HasColumnType("bigint");

                    b.Property<long>("WeaponModSkinId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("WeaponModSkinId");

                    b.HasIndex("AccountUid", "WeaponModSkinId")
                        .IsUnique();

                    b.ToTable("WeaponModSkins");
                });

            modelBuilder.Entity("NTRSimulator.Database.Entities.WeaponSkin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountUid")
                        .HasColumnType("bigint");

                    b.Property<long>("WeaponSkinId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("WeaponSkinId");

                    b.HasIndex("AccountUid", "WeaponSkinId")
                        .IsUnique();

                    b.ToTable("WeaponSkins");
                });

            modelBuilder.Entity("NTRSimulator.Database.Entities.AvgDuo", b =>
                {
                    b.HasOne("NTRSimulator.Database.Entities.Account", "Account")
                        .WithOne("AvgDuo")
                        .HasForeignKey("NTRSimulator.Database.Entities.AvgDuo", "AccountUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("NTRSimulator.Database.Entities.Costume", b =>
                {
                    b.HasOne("NTRSimulator.Database.Entities.Account", "Account")
                        .WithMany("Costumes")
                        .HasForeignKey("AccountUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("NTRSimulator.Database.Entities.GunEntity", b =>
                {
                    b.HasOne("NTRSimulator.Database.Entities.Account", "Account")
                        .WithMany("Guns")
                        .HasForeignKey("AccountUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("NTRSimulator.Database.Entities.Item", b =>
                {
                    b.HasOne("NTRSimulator.Database.Entities.Account", "Account")
                        .WithMany("Items")
                        .HasForeignKey("AccountUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("NTRSimulator.Database.Entities.Weapon", b =>
                {
                    b.HasOne("NTRSimulator.Database.Entities.Account", "Account")
                        .WithMany("Weapons")
                        .HasForeignKey("AccountUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("NTRSimulator.Database.Entities.WeaponMod", b =>
                {
                    b.HasOne("NTRSimulator.Database.Entities.Account", "Account")
                        .WithMany("WeaponMods")
                        .HasForeignKey("AccountUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("NTRSimulator.Database.Entities.WeaponModSkin", b =>
                {
                    b.HasOne("NTRSimulator.Database.Entities.Account", "Account")
                        .WithMany("WeaponModSkins")
                        .HasForeignKey("AccountUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("NTRSimulator.Database.Entities.WeaponSkin", b =>
                {
                    b.HasOne("NTRSimulator.Database.Entities.Account", "Account")
                        .WithMany("WeaponSkins")
                        .HasForeignKey("AccountUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("NTRSimulator.Database.Entities.Account", b =>
                {
                    b.Navigation("AvgDuo");

                    b.Navigation("Costumes");

                    b.Navigation("Guns");

                    b.Navigation("Items");

                    b.Navigation("WeaponModSkins");

                    b.Navigation("WeaponMods");

                    b.Navigation("WeaponSkins");

                    b.Navigation("Weapons");
                });
#pragma warning restore 612, 618
        }
    }
}
